services:
  9559-db:
    restart: "no"
    ports:
      - "5432:5432"

  9559-backend:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: .
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: .
          action: sync
          target: /app
          ignore:
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./htmlcov:/app/htmlcov
