"""add_link_changes_items

Revision ID: 33ae56e041c2
Revises: c145bc3bb106
Create Date: 2025-10-04 15:31:23.646436

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '33ae56e041c2'
down_revision = 'c145bc3bb106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cambio_item_link',
    sa.Column('id_cambio', sa.Uuid(), nullable=False),
    sa.Column('id_config_item', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_cambio'], ['cambios.id'], ),
    sa.ForeignKeyConstraint(['id_config_item'], ['items_configuracion.id'], ),
    sa.PrimaryKeyConstraint('id_cambio', 'id_config_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cambio_item_link')
    # ### end Alembic commands ###
