"""add column impacto to changes

Revision ID: 3b6df2e02eb8
Revises: 789b8f7fe905
Create Date: 2025-11-02 18:50:34.049561

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.models.changes import ImpactoCambio


# revision identifiers, used by Alembic.
revision = '3b6df2e02eb8'
down_revision = '789b8f7fe905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    impactocambio = sa.Enum(ImpactoCambio, name="impactocambio")
    impactocambio.create(op.get_bind(), checkfirst=True)
    op.add_column('cambios', sa.Column('impacto', sa.Enum('MENOR', 'SIGNIFICATIVO', 'MAYOR', name='impactocambio'), server_default='MENOR', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cambios', 'impacto')
    impactocambio = sa.Enum(ImpactoCambio, name="impactocambio")
    impactocambio.drop(op.get_bind())
    # ### end Alembic commands ###
