"""create cambios table

Revision ID: 59ed5a121bba
Revises: e23bdbf17a28
Create Date: 2025-09-25 21:46:26.176581

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59ed5a121bba'
down_revision = 'e23bdbf17a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cambios',
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridad'), nullable=False),
    sa.Column('estado', sa.Enum('RECIBIDO', 'ACEPTADO', 'RECHAZADO', 'EN_PROGRESO', 'CERRADO', name='estadocambio'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cambios')
    sa.Enum(name="estadocambio").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="prioridad").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
