"""add column fecha cierre to problem

Revision ID: 5a38fb17ecf4
Revises: b5159e816256
Create Date: 2025-10-23 22:17:19.093547

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a38fb17ecf4'
down_revision = 'b5159e816256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problemas', sa.Column('fecha_cierre', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problemas', 'fecha_cierre')
    # ### end Alembic commands ###
