"""create_relation_changes_incidents

Revision ID: 5c827f3575ce
Revises: 3b6df2e02eb8
Create Date: 2025-11-19 05:18:15.301610

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c827f3575ce'
down_revision = '3b6df2e02eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cambio_incidente_link',
    sa.Column('id_cambio', sa.Uuid(), nullable=False),
    sa.Column('id_incidentes', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_cambio'], ['cambios.id'], ),
    sa.ForeignKeyConstraint(['id_incidentes'], ['incidentes.id'], ),
    sa.PrimaryKeyConstraint('id_cambio', 'id_incidentes')
    )
    op.alter_column('cambios', 'impacto',
               existing_type=postgresql.ENUM('MENOR', 'SIGNIFICATIVO', 'MAYOR', name='impactocambio'),
               nullable=False,
               existing_server_default=sa.text("'MENOR'::impactocambio"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cambios', 'impacto',
               existing_type=postgresql.ENUM('MENOR', 'SIGNIFICATIVO', 'MAYOR', name='impactocambio'),
               nullable=True,
               existing_server_default=sa.text("'MENOR'::impactocambio"))
    op.drop_table('cambio_incidente_link')
    # ### end Alembic commands ###
