"""create incidents table and link table

Revision ID: 6e227c269e1b
Revises: 6f501603269d
Create Date: 2025-10-05 21:58:35.562391

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6e227c269e1b'
down_revision = '6f501603269d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidentes',
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.Enum('NUEVO', 'EN_PROGRESO', 'RESUELTO', 'CERRADO', name='estadoincidente'), nullable=False),
    sa.Column('categoria', sa.Enum('SOFTWARE', 'HARDWARE', 'SOLICITUD_DE_SERVICIO', 'SEGURIDAD', name='categoriaincidente'), nullable=False),
    sa.Column('responsable_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column("incidentes",
        sa.Column('prioridad', sa.Enum(name='prioridad'), nullable=False),
    )
    op.create_table('incidente_item_link',
    sa.Column('id_incidente', sa.Uuid(), nullable=False),
    sa.Column('id_config_item', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_config_item'], ['items_configuracion.id'], ),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidentes.id'], ),
    sa.PrimaryKeyConstraint('id_incidente', 'id_config_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidente_item_link')
    op.drop_table('incidentes')
    # ### end Alembic commands ###
