"""add solution column to problem

Revision ID: 789b8f7fe905
Revises: d448123eab6c
Create Date: 2025-10-31 22:40:14.904579

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '789b8f7fe905'
down_revision = 'd448123eab6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problemas', sa.Column('solucion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problemas', 'solucion')
    # ### end Alembic commands ###
