"""add responsable id to cambios

Revision ID: 859aacecb8ac
Revises: ede6874b72d6
Create Date: 2025-11-27 21:39:49.186144

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '859aacecb8ac'
down_revision = 'ede6874b72d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cambios', sa.Column('responsable_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'cambios', 'usuarios', ['responsable_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cambios', type_='foreignkey')
    op.drop_column('cambios', 'responsable_id')
    # ### end Alembic commands ###
