"""create table auditoria

Revision ID: a530f69e3eb1
Revises: 6e227c269e1b
Create Date: 2025-10-16 18:29:19.443958

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a530f69e3eb1'
down_revision = '6e227c269e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('tipo_entidad', sa.Enum('CONFIG_ITEM', 'INCIDENTE', 'CAMBIO', 'PROBLEMA', name='tipoentidad'), nullable=False),
    sa.Column('id_entidad', sa.Uuid(), nullable=False),
    sa.Column('operacion', sa.Enum('CREAR', 'ACTUALIZAR', 'ELIMINAR', name='accion'), nullable=False),
    sa.Column('actualizado_por', sa.Uuid(), nullable=False),
    sa.Column('estado_nuevo', sa.JSON(), nullable=False),
    sa.Column('fecha_acutalizacion', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditoria')
    # ### end Alembic commands ###
