"""create relation problemas-incidentes

Revision ID: b5159e816256
Revises: e1c34934113d
Create Date: 2025-10-21 22:53:39.941022

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b5159e816256'
down_revision = 'e1c34934113d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problema_incidente_link',
    sa.Column('id_problema', sa.Uuid(), nullable=False),
    sa.Column('id_incidente', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidentes.id'], ),
    sa.ForeignKeyConstraint(['id_problema'], ['problemas.id'], ),
    sa.PrimaryKeyConstraint('id_problema', 'id_incidente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problema_incidente_link')
    # ### end Alembic commands ###
