"""rename enum accion for operacion

Revision ID: b8156c78c32f
Revises: a530f69e3eb1
Create Date: 2025-10-16 19:42:18.268448

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b8156c78c32f'
down_revision = 'a530f69e3eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
