"""create table items_configuracion

Revision ID: c145bc3bb106
Revises: 59ed5a121bba
Create Date: 2025-09-27 22:03:19.279647

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c145bc3bb106'
down_revision = '59ed5a121bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_configuracion',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sa.Enum('SOFTWARE', 'HARDWARE', 'DOCUMENTACION', name='categoriaitem'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.Enum('PLANEADO', 'ENCARGADO', 'EN_CREACION', 'EN_PRUEBA', 'EN_ALMACEN', 'EN_PRODUCCION', 'EN_MANTENIMIENTO', name='estadoitem'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_configuracion')
    sa.Enum(name="estadoitem").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="categoriaitem").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
