"""rename_column_in_cambio_incidente_link

Revision ID: c7a1b264897a
Revises: 5c827f3575ce
Create Date: 2025-11-19 14:47:54.475068

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7a1b264897a'
down_revision = '5c827f3575ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cambio_incidente_link', sa.Column('id_incidente', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('cambio_incidente_link_id_incidentes_fkey'), 'cambio_incidente_link', type_='foreignkey')
    op.create_foreign_key(None, 'cambio_incidente_link', 'incidentes', ['id_incidente'], ['id'])
    op.drop_column('cambio_incidente_link', 'id_incidentes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cambio_incidente_link', sa.Column('id_incidentes', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cambio_incidente_link', type_='foreignkey')
    op.create_foreign_key(op.f('cambio_incidente_link_id_incidentes_fkey'), 'cambio_incidente_link', 'incidentes', ['id_incidentes'], ['id'])
    op.drop_column('cambio_incidente_link', 'id_incidente')
    # ### end Alembic commands ###
