"""fix typos in auditorias

Revision ID: d0a7e7d67843
Revises: b8156c78c32f
Create Date: 2025-10-16 22:37:54.905353

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0a7e7d67843'
down_revision = 'b8156c78c32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditorias',
    sa.Column('tipo_entidad', sa.Enum('CONFIG_ITEM', 'INCIDENTE', 'CAMBIO', 'PROBLEMA', name='tipoentidad'), nullable=False),
    sa.Column('id_entidad', sa.Uuid(), nullable=False),
    sa.Column('operacion', sa.Enum('CREAR', 'ACTUALIZAR', 'ELIMINAR', name='operacion'), nullable=False),
    sa.Column('actualizado_por', sa.Uuid(), nullable=False),
    sa.Column('estado_nuevo', sa.JSON(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('auditoria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('tipo_entidad', postgresql.ENUM('CONFIG_ITEM', 'INCIDENTE', 'CAMBIO', 'PROBLEMA', name='tipoentidad'), autoincrement=False, nullable=False),
    sa.Column('id_entidad', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('operacion', postgresql.ENUM('CREAR', 'ACTUALIZAR', 'ELIMINAR', name='accion'), autoincrement=False, nullable=False),
    sa.Column('actualizado_por', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('estado_nuevo', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('fecha_acutalizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], name=op.f('auditoria_actualizado_por_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('auditoria_pkey'))
    )
    op.drop_table('auditorias')
    # ### end Alembic commands ###
