"""add column fecha_cierre to cambios

Revision ID: d448123eab6c
Revises: 5a38fb17ecf4
Create Date: 2025-10-23 23:58:20.467398

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd448123eab6c'
down_revision = '5a38fb17ecf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cambios', sa.Column('fecha_cierre', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cambios', 'fecha_cierre')
    # ### end Alembic commands ###
