"""add column fecha_cierre to incident

Revision ID: e1c34934113d
Revises: d0a7e7d67843
Create Date: 2025-10-19 20:45:51.304120

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e1c34934113d'
down_revision = 'd0a7e7d67843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidentes', sa.Column('fecha_cierre', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidentes', 'fecha_cierre')
    # ### end Alembic commands ###
