"""create usuarios table

Revision ID: e23bdbf17a28
Revises: 9b1b712605c7
Create Date: 2025-09-21 15:10:05.896563

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e23bdbf17a28'
down_revision = '9b1b712605c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rol', sa.Enum('EMPLEADO', 'CLIENTE', name='rol'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contraseña_hasheada', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    sa.Enum(name="rol").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
