"""create relation changes problems

Revision ID: ede6874b72d6
Revises: c7a1b264897a
Create Date: 2025-11-19 19:32:17.710520

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ede6874b72d6'
down_revision = 'c7a1b264897a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cambio_problema_link',
    sa.Column('id_cambio', sa.Uuid(), nullable=False),
    sa.Column('id_problema', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_cambio'], ['cambios.id'], ),
    sa.ForeignKeyConstraint(['id_problema'], ['problemas.id'], ),
    sa.PrimaryKeyConstraint('id_cambio', 'id_problema')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cambio_problema_link')
    # ### end Alembic commands ###
