name: Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.4.15"
          enable-cache: true
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d 9559-backend
      # - name: Migrate DB
      #   run: uv run bash scripts/prestart.sh
      #   working-directory: .
      - name: Run tests
        # run: uv run bash scripts/tests-start.sh "Coverage for ${{ github.sha }}"
        run: make pytest
        working-directory: .
      - run: docker compose down -v --remove-orphans
